name: "Create release on tag"

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+-fork\.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set release environment variable
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/tags/}

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ env.RELEASE_VERSION }}
          body: |
            # Changes

            Synced with Lemmy upstream.

            # Usage

            Container image: `podman pull quay.io/innereq/lenny:${{ env.RELEASE_VERSION }}`.